

spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
    key-prefix: navi

aws:
  region: ap-northeast-2
  ses:
    sender: calatheas@naver.com

logging:
  level:
    root: INFO
    org.springframework.transaction.interceptor: INFO
  file:
    path: ${HOME}/logs
server:
  port: 8081
