spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
    key-prefix: navi
  web:
    resources:
      static-locations: classpath:/resources/, classpath:/docs/
  thymeleaf:
    prefix: classpath:/templates/ # default value
    check-template-location: true # default value
    suffix: .html # default value
    mode: HTML5 # default value = HTML
    cache: false # default value = false

aws:
  region: ap-northeast-2
  ses:
    sender: calatheas@naver.com

logging:
  level:
    root: INFO
    org.springframework.transaction.interceptor: INFO
  file:
    path: ${HOME}/logs
server:
  port: 8081